#!env bash

FILENAME='m8/setup/install'

if [ "$0" != "$FILENAME" ]; then
	echo "error: must be called as ${FILENAME} from project directory"
	echo "exiting"
	exit
fi

echo 
echo

for x in `ls m8/setup/tasks`; do
	echo
	echo "---------------------------------------------------"
	echo -n "### TASK: "
	echo $x	
	bash m8/setup/tasks/$x
	echo "  ...done."
done


echo
echo "---------------------------------------------------"
date
echo "setup finished"
echo
